import type { DisasterScenario } from './types';

export const SCENARIOS: DisasterScenario[] = [
  {
    id: 'flood',
    name: 'Flood',
    icon: '🌊',
    tagline: 'Person isolated for 4 hours in rising water',
    description: 'Trapped on an upper floor with rising water below. High humidity, limited mobility, and prolonged exposure to damp conditions.',
    env: {
      label: 'FLOOD',
      humidity: 92,
      aqi: 120,
      heatIndex: 39,
      detail: 'High humidity / flood exposure',
    },
    progression: [
      { hr: 78, spo2: 98, temp: 36.8, movement: 'MODERATE' },
      { hr: 88, spo2: 97, temp: 37.2, movement: 'LOW' },
      { hr: 98, spo2: 95, temp: 37.8, movement: 'LOW' },
      { hr: 108, spo2: 94, temp: 38.2, movement: 'LOW' },
      { hr: 122, spo2: 90, temp: 38.6, movement: 'STILL' },
      { hr: 138, spo2: 86, temp: 39.1, movement: 'STILL' },
    ],
  },
  {
    id: 'heatwave',
    name: 'Heatwave',
    icon: '🔥',
    tagline: 'Elderly person without power during extreme heat',
    description: 'Power outage during a heatwave. No cooling, limited water, and rising indoor temperatures over several hours.',
    env: {
      label: 'HEATWAVE',
      humidity: 35,
      aqi: 85,
      heatIndex: 47,
      detail: 'Extreme heat / no cooling',
    },
    progression: [
      { hr: 82, spo2: 97, temp: 37.0, movement: 'LOW' },
      { hr: 92, spo2: 96, temp: 37.6, movement: 'LOW' },
      { hr: 104, spo2: 95, temp: 38.3, movement: 'STILL' },
      { hr: 115, spo2: 93, temp: 39.0, movement: 'STILL' },
      { hr: 128, spo2: 90, temp: 39.7, movement: 'STILL' },
      { hr: 142, spo2: 87, temp: 40.3, movement: 'STILL' },
    ],
  },
  {
    id: 'airpollution',
    name: 'Air Pollution',
    icon: '🌫️',
    tagline: 'Person outdoors during hazardous AQI event',
    description: 'Wildfire smoke and industrial pollution create hazardous air quality. Respiratory stress builds over hours of exposure.',
    env: {
      label: 'AIR POLLUTION',
      humidity: 28,
      aqi: 385,
      heatIndex: 34,
      detail: 'Hazardous AQI / wildfire smoke',
    },
    progression: [
      { hr: 80, spo2: 96, temp: 36.9, movement: 'MODERATE' },
      { hr: 86, spo2: 94, temp: 37.1, movement: 'MODERATE' },
      { hr: 94, spo2: 91, temp: 37.4, movement: 'LOW' },
      { hr: 102, spo2: 88, temp: 37.7, movement: 'LOW' },
      { hr: 110, spo2: 85, temp: 38.0, movement: 'STILL' },
      { hr: 118, spo2: 82, temp: 38.3, movement: 'STILL' },
    ],
  },
  {
    id: 'cyclone',
    name: 'Cyclone',
    icon: '🌪️',
    tagline: 'Family sheltering during landfall, cut off for 6 hours',
    description: 'Cyclone landfall with no evacuation possible. Structural exposure, debris risk, and prolonged confinement under extreme conditions.',
    env: {
      label: 'CYCLONE',
      humidity: 88,
      aqi: 150,
      heatIndex: 36,
      detail: 'High winds / structural exposure',
    },
    progression: [
      { hr: 90, spo2: 97, temp: 37.0, movement: 'MODERATE' },
      { hr: 100, spo2: 96, temp: 37.3, movement: 'LOW' },
      { hr: 110, spo2: 94, temp: 37.8, movement: 'LOW' },
      { hr: 120, spo2: 92, temp: 38.2, movement: 'STILL' },
      { hr: 132, spo2: 89, temp: 38.7, movement: 'STILL' },
      { hr: 145, spo2: 86, temp: 39.2, movement: 'STILL' },
    ],
  },
  {
    id: 'earthquake',
    name: 'Earthquake',
    icon: '🏚️',
    tagline: 'Person trapped under debris, awaiting rescue',
    description: 'Trapped under collapsed structure. Limited air, restricted movement, crush injury risk, and unknown rescue timeline.',
    env: {
      label: 'EARTHQUAKE',
      humidity: 65,
      aqi: 200,
      heatIndex: 31,
      detail: 'Confined space / debris exposure',
    },
    progression: [
      { hr: 110, spo2: 95, temp: 37.2, movement: 'LOW' },
      { hr: 118, spo2: 93, temp: 37.5, movement: 'STILL' },
      { hr: 126, spo2: 90, temp: 37.9, movement: 'STILL' },
      { hr: 134, spo2: 87, temp: 38.3, movement: 'STILL' },
      { hr: 144, spo2: 84, temp: 38.8, movement: 'STILL' },
      { hr: 155, spo2: 80, temp: 39.3, movement: 'STILL' },
    ],
  },
];
